import "./Chart.css";
export declare const CELL_WIDTH = 80;
export declare const CELL_HEIGHT = 40;
export declare const HIGHLIGHT_LIGHT = "bg-slate-600";
export declare const HIGHLIGHT = "bg-slate-700/50";
export declare const HIGHLIGHT_DEEP = "bg-slate-800";
export declare const HOVER_ROW_COL = "bg-zinc-800";
export declare const HOVER_CELL = "bg-zinc-300/20";
export declare const HEADER_BG = "bg-zinc-800";
export declare const DEFAULT_BG = "bg-zinc-850";
export declare const TOP_ROW_BORDER = "border-b-4 border-b-zinc-500";
export declare const LEFT_COL_BORDER = "border-r-4 border-r-zinc-500";
export default function PaceChart(): import("react/jsx-runtime").JSX.Element;
